POST http://localhost:3003/users
Content-Type: application/json

{
    "name":"Camila Prado",
    "email":"mila@labenu.com",
    "password":"12345678"
}

###

POST http://localhost:3003/post
Content-Type: application/json

{
    "photo": "https://i.picsum.photos/id/0/5618/3744.jpg?hmac=3GAAioiQziMGEtLbfrdbcoenXoWAW-zlyEAMkfEdBzQ",
    "description": "testando repository",
    "type":"event",
    "authorId": "1674738291636"
}

###
GET http://localhost:3003/posts/1674738291636

###
POST http://localhost:3003/friend/29a7c461-39e8-4a0d-b655-066c761a7afd
Content-Type: application/json

{
    "userAddId": "e7035d9c-24db-4e94-bbbb-ea676319c325"
}