POST http://localhost:3003/users
Content-Type: application/json

{
    "name":"Maria",
    "email":"maria@labenu.com",
    "password":"12345678"
}

###

POST http://localhost:3003/post
Content-Type: application/json

{
    "photo": "https://i.picsum.photos/id/0/5616/3744.jpg?hmac=3GAAioiQziMGEtLbfrdbcoenXoWAW-zlyEAMkfEdBzQ",
    "description": "testando use repository",
    "type":"event",
    "authorId": "1674738291636"
}

###
GET http://localhost:3003/posts/1674741235941